name: 'portfolio-shirsendu-dev'
services:
  app:
    # image: 'ghcr.io/algostract/portfolio-shirsendu:latest'
    restart: on-failure:3
    build: .
    volumes:
      - type: bind
        source: ./static
        target: /app/static
    env_file:
      - .env.prod
    ports:
      - 4100:3000
