name: 'portfolio-shirsendu-dev'
services:
  app:
    build: .
    restart: on-failure:3
    volumes:
      - portfolio-shirsendu_static:/app/static
    env_file:
      - .env.prod
    ports:
      - 4100:3000

volumes:
  portfolio-shirsendu_static:
    external: true
