name: 'portfolio-shirsendu-dev'
services:
  app:
    build: .
    restart: on-failure:3
    volumes:
      - static:/app/static
      - data:/app/.data
    env_file:
      - .env.prod
    ports:
      - 4100:3000

volumes:
  static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./static

  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.data
